# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/5f2b4c59-8c7d-4533-b9fa-29e6745f31be";
      fsType = "btrfs";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/F240-5234";
      fsType = "vfat";
    };

    "/source" = {
      device = "/dev/disk/by-uuid/8043e8ce-5c07-4a25-9299-84e0638d2d56";
      fsType = "btrfs";
      options = [
        "ssd"
        "noatime"
        "compress=zstd:1"
        "space_cache=v2"
        "autodefrag"
        "subvol=source"
        "x-systemd.automount"
      ];
    };

    "/games" = {
      device = "/dev/disk/by-uuid/8043e8ce-5c07-4a25-9299-84e0638d2d56";
      fsType = "btrfs";
      options = [
        "ssd"
        "noatime"
        "compress=zstd:1"
        "space_cache=v2"
        "autodefrag"
        "subvol=games"
        "x-systemd.automount"
      ];
    };
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
